# frozen_string_literal: true

source 'https://rubygems.org'

gem 'feedjira'
gem 'google-cloud-firestore'
gem 'google-cloud-pubsub'
gem 'json'
gem 'nokogiri'
gem 'ons-json-logger'
gem 'rest-client'
gem 'sanitize'
